apiVersion: apps/v1
kind: Deployment
metadata:
  name: cannabis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cannabis-backend
  template:
    metadata:
      labels:
        app: cannabis-backend
    spec:
      containers:
      - name: backend
        image: <your-backend-image>
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: cannabis-backend
spec:
  selector:
    app: cannabis-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
