name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cannabis-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/cannabis-backend:latest

    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cannabis-frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/cannabis-frontend:latest
